# Documentation Update Checklist
# Run this when updating project documentation

Write-Host "============================================"
Write-Host "  DOCUMENTATION UPDATE CHECKLIST"
Write-Host "  $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
Write-Host "============================================"
Write-Host ""
Write-Host "Review and update each item as needed:"
Write-Host ""
Write-Host "[ ] 1. CLAUDE.md"
Write-Host "       - Update 'Last Updated' date"
Write-Host "       - Update 'Current State' section"
Write-Host "       - Update 'Quick Reference' if values changed"
Write-Host "       - Update 'File Map' if new docs added"
Write-Host "       - Add entry to 'Recent Activity'"
Write-Host "       - Archive old activity notes if > 5 entries"
Write-Host ""
Write-Host "[ ] 2. docs/architecture.md"
Write-Host "       - Update if system design changed"
Write-Host "       - Skip if no changes"
Write-Host ""
Write-Host "[ ] 3. docs/infrastructure.md"
Write-Host "       - Update if hosts/connections/IPs changed"
Write-Host "       - Skip if no changes"
Write-Host ""
Write-Host "[ ] 4. docs/decisions.md"
Write-Host "       - Append new decisions with date and rationale"
Write-Host "       - Skip if no new decisions"
Write-Host ""
Write-Host "[ ] 5. docs/known-issues.md"
Write-Host "       - Add new blockers/issues"
Write-Host "       - Remove resolved issues"
Write-Host "       - Update workarounds if changed"
Write-Host ""
Write-Host "[ ] 6. docs/runbooks/"
Write-Host "       - Update affected procedures"
Write-Host "       - Create new runbook if repeatable process was done"
Write-Host "       - Skip if no changes"
Write-Host ""
Write-Host "[ ] 7. docs/reference/"
Write-Host "       - Add new domain knowledge learned"
Write-Host "       - Update existing references if corrections needed"
Write-Host "       - Skip if no changes"
Write-Host ""
Write-Host "[ ] 8. .env.example"
Write-Host "       - Add new variable names if credentials were added"
Write-Host "       - Skip if no new credentials"
Write-Host ""
Write-Host "[ ] 9. scripts/"
Write-Host "       - Document new scripts in CLAUDE.md File Map"
Write-Host "       - Skip if no new scripts"
Write-Host ""
Write-Host "============================================"
Write-Host "  After completing updates, confirm to user:"
Write-Host "  - What was updated"
Write-Host "  - Current project state"
Write-Host "  - Next steps (if any)"
Write-Host "============================================"
