#!/bin/bash

# Documentation Update Checklist
# Run this when updating project documentation

echo "============================================"
echo "  DOCUMENTATION UPDATE CHECKLIST"
echo "  $(date '+%Y-%m-%d %H:%M')"
echo "============================================"
echo ""
echo "Review and update each item as needed:"
echo ""
echo "[ ] 1. CLAUDE.md"
echo "       - Update 'Last Updated' date"
echo "       - Update 'Current State' section"
echo "       - Update 'Quick Reference' if values changed"
echo "       - Update 'File Map' if new docs added"
echo "       - Add entry to 'Recent Activity'"
echo "       - Archive old activity notes if > 5 entries"
echo ""
echo "[ ] 2. docs/architecture.md"
echo "       - Update if system design changed"
echo "       - Skip if no changes"
echo ""
echo "[ ] 3. docs/infrastructure.md"
echo "       - Update if hosts/connections/IPs changed"
echo "       - Skip if no changes"
echo ""
echo "[ ] 4. docs/decisions.md"
echo "       - Append new decisions with date and rationale"
echo "       - Skip if no new decisions"
echo ""
echo "[ ] 5. docs/known-issues.md"
echo "       - Add new blockers/issues"
echo "       - Remove resolved issues"
echo "       - Update workarounds if changed"
echo ""
echo "[ ] 6. docs/runbooks/"
echo "       - Update affected procedures"
echo "       - Create new runbook if repeatable process was done"
echo "       - Skip if no changes"
echo ""
echo "[ ] 7. docs/reference/"
echo "       - Add new domain knowledge learned"
echo "       - Update existing references if corrections needed"
echo "       - Skip if no changes"
echo ""
echo "[ ] 8. .env.example"
echo "       - Add new variable names if credentials were added"
echo "       - Skip if no new credentials"
echo ""
echo "[ ] 9. scripts/"
echo "       - Document new scripts in CLAUDE.md File Map"
echo "       - Skip if no new scripts"
echo ""
echo "============================================"
echo "  After completing updates, confirm to user:"
echo "  - What was updated"
echo "  - Current project state"
echo "  - Next steps (if any)"
echo "============================================"
